#!/bin/bash

# For this script to work, put these lines in your .bashrc

#  if [[ $custom_source ]]
#  then
#    source "$custom_source"
#  fi

# tell me where your clean installation is
#export CLEAN_BASEDIR=/home/mkl/clean/clean-nightly-2017-03-24
# use a symlink to link to the current version
export CLEAN_BASEDIR=/home/mkl/clean/clean

# Scripts in clean-dev-tools need CLEAN_DEV_TOOLS set
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
export CLEAN_DEV_TOOLS="$SCRIPTPATH"

# custom_source must be enabled in .bashrc, see above.
# urxvt starts a bash, which uses custom_source
#custom_source=$CLEAN_DEV_TOOLS/clean-ide.source urxvt &

# use bash directly if you don't want to start a new terminal
custom_source=$CLEAN_DEV_TOOLS/clean-ide.source bash
